### ISSUE TITLE
NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by cowwoc** [AdoptOpenJDK/jitwatch#179]
1. Go to https://github.com/AdoptOpenJDK/jitwatch
2. Download "OpenJDK 8 binary"
3. Unzip the binary
4. Run `java -jar jitwatch-1.0.0-SNAPSHOT.jar`
5. Launcher fails with:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.adoptopenjdk.jitwatch.ui.JITWatchUI.<clinit>(JITWatchUI.java:85)
        at org.adoptopenjdk.jitwatch.launch.LaunchUI.main(LaunchUI.java:18)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
```

I'm guessing you forgot to bundle slf4j with your executable JAR file.

**Comment by chriswhocodes** [comment]
Hi, thanks for reporting this, I'll get it fixed.

In the meantime, you can still run JITWatch by running:

```git clone https://github.com/AdoptOpenJDK/jitwatch.git```

Followed by

```mvn clean install exec:java```

**Comment by chriswhocodes** [comment]
Sorry, making an executable jar for JITWatch is not on the horizon right now.
It can be invoked from the build tools (ant / maven / gradle) or using the shell scripts provided.
