### ISSUE TITLE
NumberFormatException when loading hotspot.log on OSX.

### ISSUE THREAD

**Issue by buchgr** [AdoptOpenJDK/jitwatch#237]
This happened on OSX El Capitan, with Java 8u102, just after I load the configuration file via the UI. JITWatch seems to work fine, but doesn't show the generated assembly (which I am after).

Here is my hotspot.log file: [hotspot_pid712.log.txt](https://github.com/AdoptOpenJDK/jitwatch/files/458614/hotspot_pid712.log.txt)

Please let me know if I can assist any further.

Thanks! :)

```
Exception in thread "Thread-8" java.lang.NumberFormatException: For input string: "eax"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at org.adoptopenjdk.jitwatch.model.assembly.AssemblyUtil.getValueFromAddress(AssemblyUtil.java:279)
	at org.adoptopenjdk.jitwatch.model.assembly.AssemblyLabels.instructionToLabel(AssemblyLabels.java:63)
	at org.adoptopenjdk.jitwatch.model.assembly.AssemblyLabels.newInstruction(AssemblyLabels.java:48)
	at org.adoptopenjdk.jitwatch.model.assembly.AssemblyUtil.createInstruction(AssemblyUtil.java:254)
	at org.adoptopenjdk.jitwatch.model.assembly.AssemblyUtil.parseAssembly(AssemblyUtil.java:96)
	at org.adoptopenjdk.jitwatch.core.AssemblyProcessor.complete(AssemblyProcessor.java:161)
	at org.adoptopenjdk.jitwatch.core.AssemblyProcessor.handleLine(AssemblyProcessor.java:101)
	at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.parseAssemblyLines(HotSpotLogParser.java:387)
	at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.parseLogFile(HotSpotLogParser.java:304)
	at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.processLogFile(HotSpotLogParser.java:282)
	at org.adoptopenjdk.jitwatch.ui.JITWatchUI$1.run(JITWatchUI.java:205)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by buchgr** [comment]
Maybe related to #236

**Comment by chriswhocodes** [comment]
Hi, I think your disassembler is outputting Intel format?
```
  0x000000010e09ec80: call      0x000000000e09cfa0  ;   {no_reloc}
  0x000000010e09ec85: dec       eax
  0x000000010e09ec86: mov       [esp-0x28], esp
  0x000000010e09ec8a: dec       eax
  0x000000010e09ec8b: sub       esp, 0x0000000000000080
  0x000000010e09ec91: dec       eax
  0x000000010e09ec92: mov       [esp+0x78], eax
  0x000000010e09ec96: dec       eax
  0x000000010e09ec97: mov       [esp+0x70], ecx
  0x000000010e09ec9b: dec       eat
``` 
Currently JITWatch only understands AT&T format but I have issue https://github.com/AdoptOpenJDK/jitwatch/issues/232 open to support Intel 

My AT&T format disassembly looks like:
```
  0x0000000107a9fb00: callq  0x0000000107a9eae0  ;   {no_reloc}
  0x0000000107a9fb05: mov    %rsp,-0x28(%rsp)
  0x0000000107a9fb0a: sub    $0x80,%rsp
  0x0000000107a9fb11: mov    %rax,0x78(%rsp)
  0x0000000107a9fb16: mov    %rcx,0x70(%rsp)
  0x0000000107a9fb1b: mov    %rdx,0x68(%rsp)
```

Cheers,

Chris

**Comment by buchgr** [comment]
Strange. I didn't specify anything for it to output intel syntax. I ll try forcing AT&T and see if it resolves the issue.

**Comment by chriswhocodes** [comment]
Intel assembly format now supported by https://github.com/AdoptOpenJDK/jitwatch/commit/1171c92d530b90ee9d7aa2e47d3639e321d2f357 so I'll close this issue. Please re-open if it doesn't work for you.

Cheers,

Chris
