### ISSUE TITLE
Can't run with ant

### ISSUE THREAD

**Issue by stefan-reich** [AdoptOpenJDK/jitwatch#284]
Hi, I'm using ant 1.10.3 on 64-Bit Linux with JDK 10.0.1. "ant run" gives this:

```
Buildfile: /home/stefan/dev/jitwatch-master/build.xml

jar:

init:

compile:

doJar:
      [jar] Building jar: /home/stefan/dev/jitwatch-master/core/target/jitwatch-core-1.3.0.jar

init:

compile:

doJar:
      [jar] Building jar: /home/stefan/dev/jitwatch-master/ui/target/jitwatch-ui-1.3.0.jar

run:

doRun:

doRun:
     [java] java.lang.NoClassDefFoundError: javafx/application/Application
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:199)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:835)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:227)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [java] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:448)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:469)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
     [java] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [java] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [java] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:448)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:469)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:849)
     [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:228)
     [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
     [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
     [java] Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
     [java] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
     [java] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
     [java] 	at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1149)
     [java] 	at org.apache.tools.ant.AntClassLoader.getClassFromStream(AntClassLoader.java:1317)
     [java] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1373)
     [java] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1334)
     [java] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1095)
     [java] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
     [java] 	at org.adoptopenjdk.jitwatch.launch.LaunchUI.main(LaunchUI.java:18)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:223)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
     [java] 	... 32 more
     [java] Caused by: java.lang.ClassNotFoundException: javafx.application.Application
     [java] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1385)
     [java] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1334)
     [java] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1095)
     [java] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
     [java] 	... 47 more
     [java] Java Result: -1

BUILD SUCCESSFUL
Total time: 2 seconds
```

**Comment by chriswhocodes** [comment]
Hi, this error means that JavaFX libraries were not found at compile time.

When you say you are using JDK 10.0.1 do you mean Oracle JDK10 (which should include JavaFX) or another OpenJDK build which might not include JavaFX?

**Comment by chriswhocodes** [comment]
Just tested with Oracle JDK10.0.1 on Linux and ant seems to be working.

```
chris@opencl:~/jitwatch$ $JAVA_HOME/bin/java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

chris@opencl:~/jitwatch$ ant clean jar
Buildfile: /home/chris/jitwatch/build.xml

clean:

clean:
   [delete] Deleting directory /home/chris/jitwatch/core/target

clean:
   [delete] Deleting directory /home/chris/jitwatch/ui/target

jar:

init:
    [mkdir] Created dir: /home/chris/jitwatch/core/target

compile:
    [mkdir] Created dir: /home/chris/jitwatch/core/target/classes
    [javac] Compiling 175 source files to /home/chris/jitwatch/core/target/classes
    [javac] Note: /home/chris/jitwatch/core/src/main/java/org/adoptopenjdk/jitwatch/process/javap/ReflectionJavap.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
     [copy] Copying 38 files to /home/chris/jitwatch/core/target/classes
    [mkdir] Created dir: /home/chris/jitwatch/core/target/test-classes
    [javac] Compiling 36 source files to /home/chris/jitwatch/core/target/test-classes
     [copy] Copying 1 file to /home/chris/jitwatch/core/target/test-classes

doJar:
      [jar] Building jar: /home/chris/jitwatch/core/target/jitwatch-core-1.3.0.jar

init:
    [mkdir] Created dir: /home/chris/jitwatch/ui/target

compile:
    [mkdir] Created dir: /home/chris/jitwatch/ui/target/classes
    [javac] Compiling 79 source files to /home/chris/jitwatch/ui/target/classes
     [copy] Copying 3 files to /home/chris/jitwatch/ui/target/classes
    [mkdir] Created dir: /home/chris/jitwatch/ui/target/test-classes
     [copy] Copying 1 file to /home/chris/jitwatch/ui/target/test-classes

doJar:
      [jar] Building jar: /home/chris/jitwatch/ui/target/jitwatch-ui-1.3.0.jar

BUILD SUCCESSFUL
Total time: 3 seconds
```
