### ISSUE TITLE
java.lang.NullPointerException while parsing Zing 11 log

### ISSUE THREAD

**Issue by mells82** [AdoptOpenJDK/jitwatch#311]
While trying to parse a Hotspot log file generated by Zing 11 JVM, I face the following exception:

Exception in thread "Thread-8" java.lang.NullPointerException
	at org.adoptopenjdk.jitwatch.util.VmVersionDetector.getMajorVersionFromHotSpotTag(VmVersionDetector.java:34)
	at org.adoptopenjdk.jitwatch.parser.hotspot.HotSpotLogParser.handleVmVersion(HotSpotLogParser.java:395)
	at org.adoptopenjdk.jitwatch.parser.hotspot.HotSpotLogParser.handleTag(HotSpotLogParser.java:353)
	at org.adoptopenjdk.jitwatch.parser.hotspot.HotSpotLogParser.parseHeaderLines(HotSpotLogParser.java:99)
	at org.adoptopenjdk.jitwatch.parser.hotspot.HotSpotLogParser.parseLogFile(HotSpotLogParser.java:125)
	at org.adoptopenjdk.jitwatch.parser.AbstractLogParser.processLogFile(AbstractLogParser.java:365)
	at org.adoptopenjdk.jitwatch.ui.main.JITWatchUI$1.run(JITWatchUI.java:240)
	at java.lang.Thread.run(Thread.java:748)

The flags used to generate the Zing Hotspot file are
-XX:+PrintCompilation -XX:+PrintCompileDateStamps -XX:+TraceDeoptimization -XX:-DisplayVMOutput -XX:+LogVMOutput -XX:LogFile=vmout.log

Zing version used: 11.0.3.0.101-zing_19.07.0.0-b4-product

The JITWatcher tool is launched using Zulu FX 8u222

**Comment by chriswhocodes** [comment]
Thanks for reporting. Looks like I need to update the version detection code.

**Comment by chriswhocodes** [comment]
My Zing OSS license expired so I've requested a renewal from Azul.

**Comment by chriswhocodes** [comment]
Got my renewed Azul Zing license for OSS work :)
Will track down this bug asap.

**Comment by chriswhocodes** [comment]
![selectVM](https://user-images.githubusercontent.com/1898314/69000554-6d189e00-08c9-11ea-99d9-f12406c53ab7.png)

Hi,  Just wanted to check that you are selecting Zing as the VM type as per the above screenshot? 
The stack trace you posted looks like JITWatch thinks it's parsing a HotSpot log file?

**Comment by chriswhocodes** [comment]
Closing this as I think the Zing parser was not selected. Please comment if this is not the case. Thanks.
